name: aicai_assistant
description: AI财 - 智能AI助手，你的互联网嘴替
publish_to: "none"
version: 3.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  flutter_file_dialog: ^3.0.2
  file_picker: ^8.0.0
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  flutter_markdown: ^0.6.18
  flutter_math_fork: ^0.7.2
  markdown: ^7.2.1
  syncfusion_flutter_pdf: ^24.2.8
  archive: ^3.6.1
  xml: ^6.5.0
  pdfx: ^2.6.0
  image: ^4.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
